document.getElementById("CAN_CFG_NUMBER_OF_CONTROLLERS").value = data[0].CAN_CFG_NUMBER_OF_CONTROLLERS;
CAN_CFG_NUMBER_OF_CONTROLLERSvalidate();
document.getElementById("CAN_WAKUP_ENABLE").value = data[0].CAN_WAKUP_ENABLE;
document.getElementById("CAN0_CONTROLLER_BASE_ADDRESS").value = data[0].CAN0_CONTROLLER_BASE_ADDRESS;
document.getElementById("CAN0_PERIPHERAL_CLOCK").value = data[0].CAN0_PERIPHERAL_CLOCK;
CAN0_PERIPHERAL_CLOCKvalidate();
document.getElementById("CAN0_BAUD_RATE").value = data[0].CAN0_BAUD_RATE;
document.getElementById("CAN0_TSEG1").value = data[0].CAN0_TSEG1;
CAN0_TSEG1validate();
document.getElementById("CAN0_TSEG2").value = data[0].CAN0_TSEG2;
CAN0_TSEG2validate();
document.getElementById("CAN0_SJW").value = data[0].CAN0_SJW;
CAN0_SJWvalidate();
document.getElementById("CAN0_NSAMP").value = data[0].CAN0_NSAMP;
document.getElementById("CAN0_CFG_BUSOFF_INTERRUPT").value = data[0].CAN0_CFG_BUSOFF_INTERRUPT;
document.getElementById("CAN0_CFG_RX_INTERRUPT").value = data[0].CAN0_CFG_RX_INTERRUPT;
document.getElementById("CAN0_CFG_TX_INTERRUPT").value = data[0].CAN0_CFG_TX_INTERRUPT;
document.getElementById("CAN0_CFG_WAKEUP_INTERRUPT").value = data[0].CAN0_CFG_WAKEUP_INTERRUPT;
document.getElementById("CAN0_MIN_NUMBER_OF_BASIC_BUFFERS_TX").value = data[0].CAN0_MIN_NUMBER_OF_BASIC_BUFFERS_TX;
CAN0_MIN_NUMBER_OF_BASIC_BUFFERS_TXvalidate();
document.getElementById("CAN0_MIN_NUMBER_OF_BASIC_BUFFERS_RX").value = data[0].CAN0_MIN_NUMBER_OF_BASIC_BUFFERS_RX;
CAN0_MIN_NUMBER_OF_BASIC_BUFFERS_RXvalidate();
