
 document.getElementById("IS1_100_enable").checked = (data.IS1_100_enable == "on" ? true : false);
document.getElementById("IS1_100_msg_type_no_of_events").value = data.IS1_100_msg_type_no_of_events;
document.getElementById("IS3_500_enable").checked = (data.IS3_500_enable == "on" ? true : false);
document.getElementById("IS3_500_msg_type_no_of_events").value = data.IS3_500_msg_type_no_of_events;
document.getElementById("IS_SP_enable").checked = (data.IS_SP_enable == "on" ? true : false);
document.getElementById("IS_SP_msg_type_no_of_events").value = data.IS_SP_msg_type_no_of_events;
document.getElementById("IS_TEST_enable").checked = (data.IS_TEST_enable == "on" ? true : false);
document.getElementById("IS_TEST_msg_type_no_of_events").value = data.IS_TEST_msg_type_no_of_events;
 document.getElementById("IS_ACTIVE_enable").checked = (data.IS_ACTIVE_enable == "on" ? true : false);
document.getElementById("IS_ACTIVE_msg_type_no_of_events").value = data.IS_ACTIVE_msg_type_no_of_events;
document.getElementById("IS_DIAG_RES_enable").checked = (data.IS_DIAG_RES_enable == "on" ? true : false);
document.getElementById("IS_DIAG_RES_msg_type_no_of_events").value = data.IS_DIAG_RES_msg_type_no_of_events;
 document.getElementById("EMS1_10_enable").checked = (data.EMS1_10_enable == "on" ? true : false);
document.getElementById("EMS1_10_msg_type_no_of_events").value = data.EMS1_10_msg_type_no_of_events;
document.getElementById("EMS2_10_enable").checked = (data.EMS2_10_enable == "on" ? true : false);
document.getElementById("EMS2_10_msg_type_no_of_events").value = data.EMS2_10_msg_type_no_of_events;
document.getElementById("EMS3_10_enable").checked = (data.EMS3_10_enable == "on" ? true : false);
document.getElementById("EMS3_10_msg_type_no_of_events").value = data.EMS3_10_msg_type_no_of_events;
document.getElementById("EMS4_20_enable").checked = (data.EMS4_20_enable == "on" ? true : false);
document.getElementById("EMS4_20_msg_type_no_of_events").value = data.EMS4_20_msg_type_no_of_events;
document.getElementById("EMS5_500_enable").checked = (data.EMS5_500_enable == "on" ? true : false);
document.getElementById("EMS5_500_msg_type_no_of_events").value = data.EMS5_500_msg_type_no_of_events;
document.getElementById("EMS6_500_enable").checked = (data.EMS6_500_enable == "on" ? true : false);
document.getElementById("EMS6_500_msg_type_no_of_events").value = data.EMS6_500_msg_type_no_of_events;
document.getElementById("EMS8_10_enable").checked = (data.EMS8_10_enable == "on" ? true : false);
document.getElementById("EMS8_10_msg_type_no_of_events").value = data.EMS8_10_msg_type_no_of_events;
document.getElementById("ESC1_10_enable").checked = (data.ESC1_10_enable == "on" ? true : false);
document.getElementById("ESC1_10_msg_type_no_of_events").value = data.ESC1_10_msg_type_no_of_events;
document.getElementById("ESC2_10_enable").checked = (data.ESC2_10_enable == "on" ? true : false);
document.getElementById("ESC2_10_msg_type_no_of_events").value = data.ESC2_10_msg_type_no_of_events;
document.getElementById("ESC3_20_enable").checked = (data.ESC3_20_enable == "on" ? true : false);
document.getElementById("ESC3_20_msg_type_no_of_events").value = data.ESC3_20_msg_type_no_of_events;
document.getElementById("FATC1_200_enable").checked = (data.FATC1_200_enable == "on" ? true : false);
document.getElementById("FATC1_200_msg_type_no_of_events").value = data.FATC1_200_msg_type_no_of_events;
document.getElementById("IC1_100_enable").checked = (data.IC1_100_enable == "on" ? true : false);
document.getElementById("IC1_100_msg_type_no_of_events").value = data.IC1_100_msg_type_no_of_events;
document.getElementById("IC2_100_enable").checked = (data.IC2_100_enable == "on" ? true : false);
document.getElementById("IC2_100_msg_type_no_of_events").value = data.IC2_100_msg_type_no_of_events;
document.getElementById("ICUA2_100_enable").checked = (data.ICUA2_100_enable == "on" ? true : false);
document.getElementById("ICUA2_100_msg_type_no_of_events").value = data.ICUA2_100_msg_type_no_of_events;
document.getElementById("ICUA2_SP_enable").checked = (data.ICUA2_SP_enable == "on" ? true : false);
document.getElementById("ICUA2_SP_msg_type_no_of_events").value = data.ICUA2_SP_msg_type_no_of_events;
document.getElementById("ICUA_TEST_enable").checked = (data.ICUA_TEST_enable == "on" ? true : false);
document.getElementById("ICUA_TEST_msg_type_no_of_events").value = data.ICUA_TEST_msg_type_no_of_events;
document.getElementById("MBFM1_100_enable").checked = (data.MBFM1_100_enable == "on" ? true : false);
document.getElementById("MBFM1_100_msg_type_no_of_events").value = data.MBFM1_100_msg_type_no_of_events;
document.getElementById("MBFM5_100_enable").checked = (data.MBFM5_100_enable == "on" ? true : false);
document.getElementById("MBFM5_100_msg_type_no_of_events").value = data.MBFM5_100_msg_type_no_of_events;
document.getElementById("MBFM6_100_enable").checked = (data.MBFM6_100_enable == "on" ? true : false);
document.getElementById("MBFM6_100_msg_type_no_of_events").value = data.MBFM6_100_msg_type_no_of_events;
document.getElementById("MBFM7_100_enable").checked = (data.MBFM7_100_enable == "on" ? true : false);
document.getElementById("MBFM7_100_msg_type_no_of_events").value = data.MBFM7_100_msg_type_no_of_events;
document.getElementById("MBFM_RPAS1_20_enable").checked = (data.MBFM_RPAS1_20_enable == "on" ? true : false);
document.getElementById("MBFM_RPAS1_20_msg_type_no_of_events").value = data.MBFM_RPAS1_20_msg_type_no_of_events;
document.getElementById("MBFM_RPAS2_100_enable").checked = (data.MBFM_RPAS2_100_enable == "on" ? true : false);
document.getElementById("MBFM_RPAS2_100_msg_type_no_of_events").value = data.MBFM_RPAS2_100_msg_type_no_of_events;
document.getElementById("MBFM_RPAS3_20_enable").checked = (data.MBFM_RPAS3_20_enable == "on" ? true : false);
document.getElementById("MBFM_RPAS3_20_msg_type_no_of_events").value = data.MBFM_RPAS3_20_msg_type_no_of_events;
document.getElementById("RVC1_100_enable").checked = (data.RVC1_100_enable == "on" ? true : false);
document.getElementById("RVC1_100_msg_type_no_of_events").value = data.RVC1_100_msg_type_no_of_events;
document.getElementById("SRS1_20_enable").checked = (data.SRS1_20_enable == "on" ? true : false);
document.getElementById("SRS1_20_msg_type_no_of_events").value = data.SRS1_20_msg_type_no_of_events;
 document.getElementById("GLOBAL_DIAG_REQ_enable").checked = (data.GLOBAL_DIAG_REQ_enable == "on" ? true : false);
document.getElementById("GLOBAL_DIAG_REQ_msg_type_no_of_events").value = data.GLOBAL_DIAG_REQ_msg_type_no_of_events;
document.getElementById("IS_DIAG_REQ_enable").checked = (data.IS_DIAG_REQ_enable == "on" ? true : false);
document.getElementById("IS_DIAG_REQ_msg_type_no_of_events").value = data.IS_DIAG_REQ_msg_type_no_of_events;
document.getElementById("MBFM_ACTIVE_enable").checked = (data.MBFM_ACTIVE_enable == "on" ? true : false);
document.getElementById("MBFM_ACTIVE_msg_type_no_of_events").value = data.MBFM_ACTIVE_msg_type_no_of_events;
document.getElementById("MBFM_WAKEUP_enable").checked = (data.MBFM_WAKEUP_enable == "on" ? true : false);
document.getElementById("MBFM_WAKEUP_msg_type_no_of_events").value = data.MBFM_WAKEUP_msg_type_no_of_events;
