document.getElementById("NM_CHANNELS").value = data[0].NM_CHANNELS;
NM_CHANNELSvalidate();
document.getElementById("CANNM_PASSIVE_MODE_ENABLED").value = data[0].CANNM_PASSIVE_MODE_ENABLED;
document.getElementById("CANNM_IMMEDIATE_TXCONF_ENABLED").value = data[0].CANNM_IMMEDIATE_TXCONF_ENABLED;
document.getElementById("CANNM_IMMEDIATE_RESTART_ENABLED").value = data[0].CANNM_IMMEDIATE_RESTART_ENABLED;
document.getElementById("CANNM_BUS_LOAD_REDUCTION_ENABLED").value = data[0].CANNM_BUS_LOAD_REDUCTION_ENABLED;
document.getElementById("CANNM_NODE_DETECTION_ENABLED").value = data[0].CANNM_NODE_DETECTION_ENABLED;
document.getElementById("CANNM_REMOTE_SLEEP_IND_ENABLED").value = data[0].CANNM_REMOTE_SLEEP_IND_ENABLED;
document.getElementById("CANNM_REPEAT_MSG_IND_ENABLED").value = data[0].CANNM_REPEAT_MSG_IND_ENABLED;
document.getElementById("CANNM_USER_DATA_ENABLED").value = data[0].CANNM_USER_DATA_ENABLED;
document.getElementById("CanNmComUserDataSupport").value = data[0].CanNmComUserDataSupport;
document.getElementById("CANNM_BUS_SYNCHRONIZATION_ENABLED").value = data[0].CANNM_BUS_SYNCHRONIZATION_ENABLED;
document.getElementById("CanNmActiveWakeupBitEnabled").value = data[0].CanNmActiveWakeupBitEnabled;
document.getElementById("CanNmRetryFirstMessageRequest").value = data[0].CanNmRetryFirstMessageRequest;
document.getElementById("NM_DIAG_COMMCTRL_SUPPORT").value = data[0].NM_DIAG_COMMCTRL_SUPPORT;
document.getElementById("CANNM_COORDINATOR_SYNC_SUPPORT").value = data[0].CANNM_COORDINATOR_SYNC_SUPPORT;
document.getElementById("CanNmCarWakeUpRxEnabled").value = data[0].CanNmCarWakeUpRxEnabled;
document.getElementById("CanNmCarWakeUpFilterEnabled").value = data[0].CanNmCarWakeUpFilterEnabled;
document.getElementById("CanNmPnEnabled").value = data[0].CanNmPnEnabled;
document.getElementById("CanNmPnHandleMultipleNetworkRequests").value = data[0].CanNmPnHandleMultipleNetworkRequests;
document.getElementById("CanNmAllNmMessagesKeepAwake").value = data[0].CanNmAllNmMessagesKeepAwake;
document.getElementById("CanNmPnEiraCalcEnabled").value = data[0].CanNmPnEiraCalcEnabled;
document.getElementById("CanNmPnEraCalcEnabled").value = data[0].CanNmPnEraCalcEnabled;
document.getElementById("NM_TYPE").value = data[0].NM_TYPE;
document.getElementById("CANNM_MAX_DATA_LENGTH").value = data[0].CANNM_MAX_DATA_LENGTH;
CANNM_MAX_DATA_LENGTHvalidate();
document.getElementById("CANNM_NODEID").value = data[0].CANNM_NODEID;
document.getElementById("CANNM_CH0_WAKE_MASK").value = data[0].CANNM_CH0_WAKE_MASK;
document.getElementById("NM_CBV_PARTIAL_NETWORK_INFORMATION_BIT").value = data[0].NM_CBV_PARTIAL_NETWORK_INFORMATION_BIT;
document.getElementById("NM_20MS_OF_100HZ").value = data[0].NM_20MS_OF_100HZ;
NM_20MS_OF_100HZvalidate();
document.getElementById("NM_NUMBER_OF_IMMIDIATE_MESSAGES").value = data[0].NM_NUMBER_OF_IMMIDIATE_MESSAGES;
NM_NUMBER_OF_IMMIDIATE_MESSAGESvalidate();
document.getElementById("NM_MSG_CYCLE_OFFSET").value = data[0].NM_MSG_CYCLE_OFFSET;
NM_MSG_CYCLE_OFFSETvalidate();
document.getElementById("NM_IMM_CYCLE_TIME").value = data[0].NM_IMM_CYCLE_TIME;
NM_IMM_CYCLE_TIMEvalidate();
document.getElementById("NmImmTransmissions").value = data[0].NmImmTransmissions;
NmImmTransmissionsvalidate();
document.getElementById("NmReducedTime").value = data[0].NmReducedTime;
NmReducedTimevalidate();
document.getElementById("RemoteSleepIndTime").value = data[0].RemoteSleepIndTime;
RemoteSleepIndTimevalidate();
document.getElementById("CarWakeBytePos").value = data[0].CarWakeBytePos;
CarWakeBytePosvalidate();
document.getElementById("CarWakeBitPos").value = data[0].CarWakeBitPos;
CarWakeBitPosvalidate();
document.getElementById("CarWakeFltrNodeId").value = data[0].CarWakeFltrNodeId;
CarWakeFltrNodeIdvalidate();
document.getElementById("NmPnInfoLength").value = data[0].NmPnInfoLength;
NmPnInfoLengthvalidate();
document.getElementById("NmPnInfoOffset").value = data[0].NmPnInfoOffset;
NmPnInfoOffsetvalidate();
document.getElementById("NmPnResetTime").value = data[0].NmPnResetTime;
NmPnResetTimevalidate();
