document.getElementById("VTP_NUM_CHANNEL_COUNT").value = data[0].VTP_NUM_CHANNEL_COUNT;
VTP_NUM_CHANNEL_COUNTvalidate();
document.getElementById("CANTP_PERIODICITY").value = data[0].CANTP_PERIODICITY;
CANTP_PERIODICITYvalidate();
document.getElementById("VTP_FC_SUPPORT").value = data[0].VTP_FC_SUPPORT;
document.getElementById("VTP_WAITFC_SUPPORT").value = data[0].VTP_WAITFC_SUPPORT;
document.getElementById("VTP_TransmitCB_SUPPORT").value = data[0].VTP_TransmitCB_SUPPORT;
document.getElementById("VTP_ReceiveCB_SUPPORT").value = data[0].VTP_ReceiveCB_SUPPORT;
document.getElementById("VTP_ReceiveQueue_SUPPORT").value = data[0].VTP_ReceiveQueue_SUPPORT;
document.getElementById("VTP_TransmitOnINT_SUPPORT").value = data[0].VTP_TransmitOnINT_SUPPORT;
document.getElementById("VTP_TURING_SUPPORT").value = data[0].VTP_TURING_SUPPORT;
document.getElementById("VTP_PADDING_SUPPORT").value = data[0].VTP_PADDING_SUPPORT;
document.getElementById("VTP_PADDING_VALUE").value = data[0].VTP_PADDING_VALUE;
document.getElementById("N_As_Tx_CONFIRMATION_TIMEOUT").value = data[0].N_As_Tx_CONFIRMATION_TIMEOUT;
N_As_Tx_CONFIRMATION_TIMEOUTvalidate();
document.getElementById("N_Bs_FLOW_CONTROL_TIMEOUT").value = data[0].N_Bs_FLOW_CONTROL_TIMEOUT;
N_Bs_FLOW_CONTROL_TIMEOUTvalidate();
document.getElementById("N_Cs_TX_CF_Timeout").value = data[0].N_Cs_TX_CF_Timeout;
N_Cs_TX_CF_Timeoutvalidate();
document.getElementById("N_WFTmax_No_OF_WAIT_FRAMES").value = data[0].N_WFTmax_No_OF_WAIT_FRAMES;
N_WFTmax_No_OF_WAIT_FRAMESvalidate();
document.getElementById("Stmin").value = data[0].Stmin;
Stminvalidate();
document.getElementById("Blocksize").value = data[0].Blocksize;
Blocksizevalidate();
document.getElementById("N_Cr_Rx_CF_Timeout").value = data[0].N_Cr_Rx_CF_Timeout;
N_Cr_Rx_CF_Timeoutvalidate();
